import type { IServerlessPanelData } from ".";

const GRPCommonConfiguration: IServerlessPanelData["configuration"] = {
  username: {
    required: true,
    type: "string",
    section: "general",
    description: "Github Username",
    cacheId: "github_username",
  },
  locale: {
    type: "select",
    options: [
      "ar",
      "cn",
      "cs",
      "de",
      "en",
      "bn",
      "es",
      "fr",
      "hu",
      "it",
      "ja",
      "kr",
      "nl",
      "pt-pt",
      "pt-br",
      "np",
      "el",
      "ru",
      "uk-ua",
      "id",
      "my",
      "sk",
      "tr",
      "pl",
    ],
    section: "general",
    description: "Set the language in the card",
  },
  theme: {
    type: "select",
    options: [
      "default",
      "default_repocard",
      "dark",
      "radical",
      "merko",
      "gruvbox",
      "tokyonight",
      "onedark",
      "cobalt",
      "synthwave",
      "highcontrast",
      "dracula",
      "prussian",
      "monokai",
      "vue",
      "vue-dark",
      "shades-of-purple",
      "nightowl",
      "buefy",
      "blue-green",
      "algolia",
      "great-gatsby",
      "darcula",
      "bear",
      "solarized-dark",
      "solarized-light",
      "chartreuse-dark",
      "nord",
      "gotham",
      "material-palenight",
      "graywhite",
      "vision-friendly-dark",
      "ayu-mirage",
      "midnight-purple",
      "calm",
      "flag-india",
      "omni",
      "react",
      "jolly",
      "maroongold",
      "yeblu",
      "blueberry",
      "slateorange",
      "kacho_ga",
      "outrun",
      "ocean_dark",
      "city_lights",
      "github_dark",
      "discord_old_blurple",
    ],
    section: "theme",
    description: "Choose the card theme",
  },
  title_color: {
    type: "color",
    section: "theme",
    description: "Set Card's title color",
  },
  text_color: {
    type: "color",
    section: "theme",
    description: "Set Body text color",
  },
  icon_color: {
    type: "color",
    section: "theme",
    description: "Set Icons color if available",
  },
  border_color: {
    type: "color",
    section: "theme",
    description: "Set Card's border color",
  },
  bg_color: {
    type: "color",
    gradient: true,
    section: "theme",
    description: "Card's background color, support gradient",
  },
  hide_border: {
    type: "boolean",
    section: "appearance",
    description: "Whether Hide the card's border",
  },
  border_radius: {
    type: "number",
    section: "appearance",
    description: "Corner rounding of the card",
  },
  cache_seconds: {
    type: "number",
    section: "data",
    min: 1800,
    max: 86400,
    description: "Set the cache header manually",
  },
};

export default GRPCommonConfiguration;
