import type { IServerlessPanelData } from ".";

const GithubStats: IServerlessPanelData = {
  title: "Github Stats",
  type: "serverless",
  configuration: {
    username: {
      required: true,
      type: "string",
      section: "general",
      description: "Github Username",
    },
    locale: {
      type: "select",
      options: [
        "ar",
        "cn",
        "cs",
        "de",
        "en",
        "bn",
        "es",
        "fr",
        "hu",
        "it",
        "ja",
        "kr",
        "nl",
        "pt-pt",
        "pt-br",
        "np",
        "el",
        "ru",
        "uk-ua",
        "id",
        "my",
        "sk",
        "tr",
        "pl",
      ],
      section: "general",
      description: "Set the language in the card",
    },
    theme: {
      type: "select",
      options: [
        "default",
        "default_repocard",
        "dark",
        "radical",
        "merko",
        "gruvbox",
        "tokyonight",
        "onedark",
        "cobalt",
        "synthwave",
        "highcontrast",
        "dracula",
        "prussian",
        "monokai",
        "vue",
        "vue-dark",
        "shades-of-purple",
        "nightowl",
        "buefy",
        "blue-green",
        "algolia",
        "great-gatsby",
        "darcula",
        "bear",
        "solarized-dark",
        "solarized-light",
        "chartreuse-dark",
        "nord",
        "gotham",
        "material-palenight",
        "graywhite",
        "vision-friendly-dark",
        "ayu-mirage",
        "midnight-purple",
        "calm",
        "flag-india",
        "omni",
        "react",
        "jolly",
        "maroongold",
        "yeblu",
        "blueberry",
        "slateorange",
        "kacho_ga",
        "outrun",
        "ocean_dark",
        "city_lights",
        "github_dark",
        "discord_old_blurple",
      ],
      section: "theme",
      description: "Choose the card theme",
    },
    title_color: {
      type: "color",
      section: "theme",
      description: "Card's title color",
    },
    text_color: {
      type: "color",
      section: "theme",
    },
    icon_color: {
      type: "color",
      section: "theme",
    },
    border_color: {
      type: "color",
      section: "theme",
    },
    bg_color: {
      type: "color",
      section: "theme",
    },
    hide_border: {
      type: "boolean",
      section: "appearance",
    },
    border_radius: {
      type: "number",
      section: "appearance",
      description: "Corner rounding of the card",
    },
    custom_title: {
      type: "string",
      section: "appearance",
    },
    hide_title: {
      type: "boolean",
      section: "appearance",
    },
    hide_rank: {
      type: "boolean",
      section: "appearance",
    },
    show_icons: {
      type: "boolean",
      section: "appearance",
    },
    line_height: {
      type: "number",
      section: "appearance",
    },
    disable_animations: {
      type: "boolean",
      section: "appearance",
    },
    cache_seconds: {
      type: "number",
      section: "data",
    },
    hide: {
      type: "string",
      section: "data",
    },
    include_all_commits: {
      type: "boolean",
      section: "data",
    },
    count_private: {
      type: "boolean",
      section: "data",
    },
  },
  requestUrl: "https://github-readme-stats.vercel.app/api",
};

export default GithubStats;
